export { default as Navbar } from './Navbar/Navbar'
export { default as Footer } from './Footer/Footer'
export { default as ComingSoon } from './Main/ComingSoon'
export { default as About } from './Main/About'
export { default as Blog } from './Main/Blog'
export { default as Contact } from './Main/Contact'
export { default as Github } from './Github/Github'